/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aaveV2 from "./aave-v2";
export type { aaveV2 };
import type * as aaveV3 from "./aave-v3";
export type { aaveV3 };
import type * as compound from "./compound";
export type { compound };
import type * as compoundV3 from "./compound-v3";
export type { compoundV3 };
export type { IMockLending } from "./IMockLending";
