/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as transparentUpgradeableProxySol from "./TransparentUpgradeableProxy.sol";
export type { transparentUpgradeableProxySol };
export type { ProxyAdmin } from "./ProxyAdmin";
