/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iCtokenSol from "./ICtoken.sol";
export { IComptroller__factory } from "./IComptroller__factory";
