/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBurnMintERC677Helper } from "./IBurnMintERC677Helper";
export type { MockVault } from "./MockVault";
