/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iCtokenSol from "./ICtoken.sol";
export type { iCtokenSol };
export type { IComptroller } from "./IComptroller";
