/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMockLending,
  IMockLendingInterface,
} from "../../../contracts/interfaces/IMockLending";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "inBehalfOf",
        type: "address",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "inBehalfOf",
        type: "address",
      },
    ],
    name: "getBorrowedAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "healthFactor",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMockLending__factory {
  static readonly abi = _abi;
  static createInterface(): IMockLendingInterface {
    return new utils.Interface(_abi) as IMockLendingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMockLending {
    return new Contract(address, _abi, signerOrProvider) as IMockLending;
  }
}
