/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as aaveV2 from "./aave-v2";
export * as aaveV3 from "./aave-v3";
export * as compound from "./compound";
export * as compoundV3 from "./compound-v3";
export { IMockLending__factory } from "./IMockLending__factory";
