/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MonitorAaveV2 } from "./MonitorAaveV2";
export type { MonitorAaveV3 } from "./MonitorAaveV3";
export type { MonitorCompoundV2 } from "./MonitorCompoundV2";
export type { MonitorCompoundV3 } from "./MonitorCompoundV3";
export type { MonitorMockLending } from "./MonitorMockLending";
