/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockVaultSol from "./MockVault.sol";
export { MockLending__factory } from "./MockLending__factory";
