/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockVaultSol from "./MockVault.sol";
export type { mockVaultSol };
export type { MockLending } from "./MockLending";
